extends:
  - "plugin:vue-libs/recommended"
env:
  browser: true
  es6: true
parser: "vue-eslint-parser"
parserOptions:
  parser: "babel-eslint"
  ecmaVersion: 6
  sourceType: "module"
rules:
  semi: ["error", "always"]  # http://eslint.org/docs/rules/semi
  space-before-function-paren: ["error", "never"]  # http://eslint.org/docs/rules/space-before-function-paren
  # 配列やオブジェクトの最後のアイテムに,を加える事を必須としない
  comma-dangle: "off"
