extends: "stylelint-config-standard"
plugins:
  - "stylelint-scss"
rules:
  # stylelintのルールは無効にする
  at-rule-no-unknown: null
  color-hex-length: "short"
  color-no-invalid-hex: true
  indentation: 2
  length-zero-no-unit: true
  media-feature-name-no-vendor-prefix: true
  # 0.をつけることを許可
  number-leading-zero: "always"
  string-quotes: "single"
  # ,でセレクタを繋げるのをありにする
  "selector-list-comma-newline-after": "always-multi-line"
  # カラー名は使用してもいい
  #"color-named": "never"
